import {Sparkles, X, Copy} from 'lucide-react';

const AISummaryModal = ({open, onClose, noteTitle, summary, onCopyToNote, loading}) => {

  if (!open) return null;
  const body = typeof summary === 'string' ? summary : (Array.isArray(summary) ? summary.join('\n') : '');

  return (
    <div
      className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm"
      onClick={(e) => e.target === e.currentTarget && onClose()}
    >
      <div
        className="w-full max-w-lg rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 shadow-2xl overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between px-5 py-4 border-b border-slate-200 dark:border-slate-700">
          <div className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-primary" />
            <h2 className="font-semibold text-slate-900 dark:text-white">AI Summary</h2>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-lg text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800 hover:text-slate-700 dark:hover:text-slate-200 transition-colors"
          >
            <X className="w-5 h-5"/>
          </button>
        </div>

        <div className="px-5 py-4 max-h-[60vh] overflow-y-auto">
          {loading ? (
            <div className="flex items-center gap-3 text-slate-500 dark:text-slate-400">
              <div className="w-5 h-5 border-2 border-primary border-t-transparent rounded-full animate-spin" />
              <span>Generating summary...</span>
            </div>
          ) : (
            <>
              <p className="text-sm text-slate-600 dark:text-slate-300 mb-4">
                Here is a concise summary of the notes from <strong className="text-slate-900 dark:text-white">{noteTitle || 'this note'}</strong>:
              </p>
              <div className="text-sm text-slate-700 dark:text-slate-300 whitespace-pre-wrap leading-relaxed prose dark:prose-invert prose-p:my-2 prose-ul:my-2 prose-li:my-0">
                {body || 'No summary generated.'}
              </div>
            </>
          )}
        </div>

        <div className="px-5 py-4 border-t border-slate-200 dark:border-slate-700 flex items-center justify-between bg-slate-50/50 dark:bg-slate-800/30">
          <div className="flex items-center gap-2 text-xs text-slate-500 dark:text-slate-400">
            <Sparkles className="w-3.5 h-3.5 text-primary" />
            <span>Generated by Notely AI</span>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="px-4 py-2 rounded-lg text-sm font-medium text-slate-700 dark:text-slate-300 bg-slate-200 dark:bg-slate-700 hover:bg-slate-300 dark:hover:bg-slate-600 transition-colors"
            >
              Close
            </button>
            <button
              onClick={onCopyToNote}
              disabled={!body || loading}
              className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium text-white bg-primary hover:opacity-95 disabled:opacity-50 transition-opacity"
            >
              <Copy className="w-4 h-4" />
              Copy to Note
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AISummaryModal;